### ISSUE TITLE
have any way that I can generate my chart to svg on server side?

### ISSUE THREAD

**Issue by truyen93** [times/axisJS#102]

**Comment by aendrew** [comment]
Hi @truyen93!

Depends what you're wanting to do — technically, Axis/C3 generates SVG already; all the exportChart directive does is inline all the styles so it can be more easily used with, say, Adobe Illustrator. There  are also a few tweaks specifically for C3, e.g., ensuring the `.c3-line {fill: none;}` declaration only affects what it needs to (If you try exporting the SVG using a lib like SVG Crowbar and line charts have weird triangles on them, this is probably the reason). If you're wanting it to do that, not sure I can help you, Axis runs entirely in the browser.

That said, I'm working on [D3 plugin](https://github.com/aendrew/d3.exportSVG) to clean up and export SVG, though am flailing a bit about it because I'm not entirely sure how to do the NodeJS support. I may ultimately just make the inlining and cleaning functionalities class methods so they can be used in NodeJS more easily. PRs welcome!

**Comment by truyen93** [comment]
Thank you so much!! I will try another way.

**Comment by aendrew** [comment]
Closing as apparently resolved; please comment if you need more help! Thanks!
